apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi
        image: mgelvoleo/fastapi-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "prod"
